# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: scyllamigrate

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: scyllamigrate
    main: ./cmd
    binary: scyllamigrate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other Changes"
      order: 999

brews:
  - name: scyllamigrate
    repository:
      owner: heartwilltell
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: brew
    homepage: "https://github.com/heartwilltell/scyllamigrate"
    description: "A lightweight schema migration tool for ScyllaDB"
    license: "MIT"
    commit_author:
      name: Serhii Mariiekha
      email: heartwilltell@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install "scyllamigrate"
    test: |
      system "#{bin}/scyllamigrate", "--help"

dockers:
  - image_templates:
      - "ghcr.io/heartwilltell/scyllamigrate:{{ .Tag }}"
      - "ghcr.io/heartwilltell/scyllamigrate:v{{ .Major }}"
      - "ghcr.io/heartwilltell/scyllamigrate:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/heartwilltell/scyllamigrate:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"

release:
  github:
    owner: heartwilltell
    name: scyllamigrate
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## ScyllaDB Migration Tool {{ .Tag }}

    Welcome to this new release of scyllamigrate!
  footer: |
    ## Installation

    ### Homebrew (macOS/Linux)
    ```bash
    brew install heartwilltell/tap/scyllamigrate
    ```

    ### Go Install
    ```bash
    go install github.com/heartwilltell/scyllamigrate/cmd@{{ .Tag }}
    ```

    ### Docker
    ```bash
    docker pull ghcr.io/heartwilltell/scyllamigrate:{{ .Tag }}
    ```

    **Full Changelog**: https://github.com/heartwilltell/scyllamigrate/compare/{{ .PreviousTag }}...{{ .Tag }}

announce:
  skip: "true"
